// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(echomesh_coreFFI)
import echomesh_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_echomesh_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_echomesh_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureEchomeshCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol EchoMeshClientProtocol: AnyObject, Sendable {
    
    func addContact(peerIdHex: String, name: String) throws 
    
    func connect(relayAddress: String, relayPublicKey: Data, secretTokenHex: String?) throws 
    
    func currentState()  -> NetworkState
    
    func disconnect() throws 
    
    func getContacts() throws  -> [Contact]
    
    func getConversations() throws  -> [ConversationSummary]
    
    func getMessages(peerIdHex: String, limit: UInt32) throws  -> [MessageRecord]
    
    func pingMs()  -> UInt32
    
    func sendChatMessage(recipientPeerIdHex: String, text: String) throws  -> MessageRecord
    
    func sendMessage(to: String, text: String) throws  -> MessagePayload
    
    func sendPacket(recipient: Data, data: Data) throws 
    
    func shutdown() throws 
    
    func storagePath()  -> String
    
}
open class EchoMeshClient: EchoMeshClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_echomesh_core_fn_clone_echomeshclient(self.pointer, $0) }
    }
public convenience init(storagePath: String, listener: CoreEventsListener)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_constructor_echomeshclient_new(
        FfiConverterString.lower(storagePath),
        FfiConverterCallbackInterfaceCoreEventsListener_lower(listener),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_echomesh_core_fn_free_echomeshclient(pointer, $0) }
    }

    

    
open func addContact(peerIdHex: String, name: String)throws   {try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_add_contact(self.uniffiClonePointer(),
        FfiConverterString.lower(peerIdHex),
        FfiConverterString.lower(name),$0
    )
}
}
    
open func connect(relayAddress: String, relayPublicKey: Data, secretTokenHex: String?)throws   {try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_connect(self.uniffiClonePointer(),
        FfiConverterString.lower(relayAddress),
        FfiConverterData.lower(relayPublicKey),
        FfiConverterOptionString.lower(secretTokenHex),$0
    )
}
}
    
open func currentState() -> NetworkState  {
    return try!  FfiConverterTypeNetworkState_lift(try! rustCall() {
    uniffi_echomesh_core_fn_method_echomeshclient_current_state(self.uniffiClonePointer(),$0
    )
})
}
    
open func disconnect()throws   {try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func getContacts()throws  -> [Contact]  {
    return try  FfiConverterSequenceTypeContact.lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_get_contacts(self.uniffiClonePointer(),$0
    )
})
}
    
open func getConversations()throws  -> [ConversationSummary]  {
    return try  FfiConverterSequenceTypeConversationSummary.lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_get_conversations(self.uniffiClonePointer(),$0
    )
})
}
    
open func getMessages(peerIdHex: String, limit: UInt32)throws  -> [MessageRecord]  {
    return try  FfiConverterSequenceTypeMessageRecord.lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_get_messages(self.uniffiClonePointer(),
        FfiConverterString.lower(peerIdHex),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
open func pingMs() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_echomesh_core_fn_method_echomeshclient_ping_ms(self.uniffiClonePointer(),$0
    )
})
}
    
open func sendChatMessage(recipientPeerIdHex: String, text: String)throws  -> MessageRecord  {
    return try  FfiConverterTypeMessageRecord_lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_send_chat_message(self.uniffiClonePointer(),
        FfiConverterString.lower(recipientPeerIdHex),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func sendMessage(to: String, text: String)throws  -> MessagePayload  {
    return try  FfiConverterTypeMessagePayload_lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_send_message(self.uniffiClonePointer(),
        FfiConverterString.lower(to),
        FfiConverterString.lower(text),$0
    )
})
}
    
open func sendPacket(recipient: Data, data: Data)throws   {try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_send_packet(self.uniffiClonePointer(),
        FfiConverterData.lower(recipient),
        FfiConverterData.lower(data),$0
    )
}
}
    
open func shutdown()throws   {try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_method_echomeshclient_shutdown(self.uniffiClonePointer(),$0
    )
}
}
    
open func storagePath() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_echomesh_core_fn_method_echomeshclient_storage_path(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEchoMeshClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = EchoMeshClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> EchoMeshClient {
        return EchoMeshClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: EchoMeshClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EchoMeshClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: EchoMeshClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEchoMeshClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> EchoMeshClient {
    return try FfiConverterTypeEchoMeshClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEchoMeshClient_lower(_ value: EchoMeshClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeEchoMeshClient.lower(value)
}




public struct Contact {
    public var peerId: Data
    public var name: String
    public var addedAt: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerId: Data, name: String, addedAt: UInt64) {
        self.peerId = peerId
        self.name = name
        self.addedAt = addedAt
    }
}

#if compiler(>=6)
extension Contact: Sendable {}
#endif


extension Contact: Equatable, Hashable {
    public static func ==(lhs: Contact, rhs: Contact) -> Bool {
        if lhs.peerId != rhs.peerId {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.addedAt != rhs.addedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peerId)
        hasher.combine(name)
        hasher.combine(addedAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Contact {
        return
            try Contact(
                peerId: FfiConverterData.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                addedAt: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Contact, into buf: inout [UInt8]) {
        FfiConverterData.write(value.peerId, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt64.write(value.addedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContact_lift(_ buf: RustBuffer) throws -> Contact {
    return try FfiConverterTypeContact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContact_lower(_ value: Contact) -> RustBuffer {
    return FfiConverterTypeContact.lower(value)
}


public struct ConversationSummary {
    public var peerId: Data
    public var title: String
    public var lastMessage: String?
    public var lastTimestamp: UInt64
    public var unreadCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerId: Data, title: String, lastMessage: String?, lastTimestamp: UInt64, unreadCount: UInt32) {
        self.peerId = peerId
        self.title = title
        self.lastMessage = lastMessage
        self.lastTimestamp = lastTimestamp
        self.unreadCount = unreadCount
    }
}

#if compiler(>=6)
extension ConversationSummary: Sendable {}
#endif


extension ConversationSummary: Equatable, Hashable {
    public static func ==(lhs: ConversationSummary, rhs: ConversationSummary) -> Bool {
        if lhs.peerId != rhs.peerId {
            return false
        }
        if lhs.title != rhs.title {
            return false
        }
        if lhs.lastMessage != rhs.lastMessage {
            return false
        }
        if lhs.lastTimestamp != rhs.lastTimestamp {
            return false
        }
        if lhs.unreadCount != rhs.unreadCount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peerId)
        hasher.combine(title)
        hasher.combine(lastMessage)
        hasher.combine(lastTimestamp)
        hasher.combine(unreadCount)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConversationSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConversationSummary {
        return
            try ConversationSummary(
                peerId: FfiConverterData.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                lastMessage: FfiConverterOptionString.read(from: &buf), 
                lastTimestamp: FfiConverterUInt64.read(from: &buf), 
                unreadCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ConversationSummary, into buf: inout [UInt8]) {
        FfiConverterData.write(value.peerId, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterOptionString.write(value.lastMessage, into: &buf)
        FfiConverterUInt64.write(value.lastTimestamp, into: &buf)
        FfiConverterUInt32.write(value.unreadCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversationSummary_lift(_ buf: RustBuffer) throws -> ConversationSummary {
    return try FfiConverterTypeConversationSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConversationSummary_lower(_ value: ConversationSummary) -> RustBuffer {
    return FfiConverterTypeConversationSummary.lower(value)
}


public struct IdentityKeyPair {
    public var privateKey: Data
    public var publicKey: Data
    public var publicKeyHex: String
    public var publicKeyBase58: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(privateKey: Data, publicKey: Data, publicKeyHex: String, publicKeyBase58: String) {
        self.privateKey = privateKey
        self.publicKey = publicKey
        self.publicKeyHex = publicKeyHex
        self.publicKeyBase58 = publicKeyBase58
    }
}

#if compiler(>=6)
extension IdentityKeyPair: Sendable {}
#endif


extension IdentityKeyPair: Equatable, Hashable {
    public static func ==(lhs: IdentityKeyPair, rhs: IdentityKeyPair) -> Bool {
        if lhs.privateKey != rhs.privateKey {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.publicKeyHex != rhs.publicKeyHex {
            return false
        }
        if lhs.publicKeyBase58 != rhs.publicKeyBase58 {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(privateKey)
        hasher.combine(publicKey)
        hasher.combine(publicKeyHex)
        hasher.combine(publicKeyBase58)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentityKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityKeyPair {
        return
            try IdentityKeyPair(
                privateKey: FfiConverterData.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf), 
                publicKeyHex: FfiConverterString.read(from: &buf), 
                publicKeyBase58: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: IdentityKeyPair, into buf: inout [UInt8]) {
        FfiConverterData.write(value.privateKey, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
        FfiConverterString.write(value.publicKeyHex, into: &buf)
        FfiConverterString.write(value.publicKeyBase58, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityKeyPair_lift(_ buf: RustBuffer) throws -> IdentityKeyPair {
    return try FfiConverterTypeIdentityKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityKeyPair_lower(_ value: IdentityKeyPair) -> RustBuffer {
    return FfiConverterTypeIdentityKeyPair.lower(value)
}


public struct MessagePayload {
    public var id: String
    public var sender: String
    public var recipient: String
    public var content: String
    public var timestamp: UInt64
    public var status: DeliveryStatus

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, sender: String, recipient: String, content: String, timestamp: UInt64, status: DeliveryStatus) {
        self.id = id
        self.sender = sender
        self.recipient = recipient
        self.content = content
        self.timestamp = timestamp
        self.status = status
    }
}

#if compiler(>=6)
extension MessagePayload: Sendable {}
#endif


extension MessagePayload: Equatable, Hashable {
    public static func ==(lhs: MessagePayload, rhs: MessagePayload) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.sender != rhs.sender {
            return false
        }
        if lhs.recipient != rhs.recipient {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(sender)
        hasher.combine(recipient)
        hasher.combine(content)
        hasher.combine(timestamp)
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessagePayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessagePayload {
        return
            try MessagePayload(
                id: FfiConverterString.read(from: &buf), 
                sender: FfiConverterString.read(from: &buf), 
                recipient: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterUInt64.read(from: &buf), 
                status: FfiConverterTypeDeliveryStatus.read(from: &buf)
        )
    }

    public static func write(_ value: MessagePayload, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.sender, into: &buf)
        FfiConverterString.write(value.recipient, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterUInt64.write(value.timestamp, into: &buf)
        FfiConverterTypeDeliveryStatus.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessagePayload_lift(_ buf: RustBuffer) throws -> MessagePayload {
    return try FfiConverterTypeMessagePayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessagePayload_lower(_ value: MessagePayload) -> RustBuffer {
    return FfiConverterTypeMessagePayload.lower(value)
}


public struct MessageRecord {
    public var id: String
    public var conversationPeerId: Data
    public var senderPeerId: Data
    public var text: String
    public var timestamp: UInt64
    public var isOutgoing: Bool
    public var status: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, conversationPeerId: Data, senderPeerId: Data, text: String, timestamp: UInt64, isOutgoing: Bool, status: UInt8) {
        self.id = id
        self.conversationPeerId = conversationPeerId
        self.senderPeerId = senderPeerId
        self.text = text
        self.timestamp = timestamp
        self.isOutgoing = isOutgoing
        self.status = status
    }
}

#if compiler(>=6)
extension MessageRecord: Sendable {}
#endif


extension MessageRecord: Equatable, Hashable {
    public static func ==(lhs: MessageRecord, rhs: MessageRecord) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.conversationPeerId != rhs.conversationPeerId {
            return false
        }
        if lhs.senderPeerId != rhs.senderPeerId {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.isOutgoing != rhs.isOutgoing {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(conversationPeerId)
        hasher.combine(senderPeerId)
        hasher.combine(text)
        hasher.combine(timestamp)
        hasher.combine(isOutgoing)
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageRecord {
        return
            try MessageRecord(
                id: FfiConverterString.read(from: &buf), 
                conversationPeerId: FfiConverterData.read(from: &buf), 
                senderPeerId: FfiConverterData.read(from: &buf), 
                text: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterUInt64.read(from: &buf), 
                isOutgoing: FfiConverterBool.read(from: &buf), 
                status: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: MessageRecord, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterData.write(value.conversationPeerId, into: &buf)
        FfiConverterData.write(value.senderPeerId, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterUInt64.write(value.timestamp, into: &buf)
        FfiConverterBool.write(value.isOutgoing, into: &buf)
        FfiConverterUInt8.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageRecord_lift(_ buf: RustBuffer) throws -> MessageRecord {
    return try FfiConverterTypeMessageRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageRecord_lower(_ value: MessageRecord) -> RustBuffer {
    return FfiConverterTypeMessageRecord.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DeliveryStatus {
    
    case sent
    case relayed
    case delivered
    case failed
}


#if compiler(>=6)
extension DeliveryStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeliveryStatus: FfiConverterRustBuffer {
    typealias SwiftType = DeliveryStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeliveryStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sent
        
        case 2: return .relayed
        
        case 3: return .delivered
        
        case 4: return .failed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DeliveryStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sent:
            writeInt(&buf, Int32(1))
        
        
        case .relayed:
            writeInt(&buf, Int32(2))
        
        
        case .delivered:
            writeInt(&buf, Int32(3))
        
        
        case .failed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeliveryStatus_lift(_ buf: RustBuffer) throws -> DeliveryStatus {
    return try FfiConverterTypeDeliveryStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeliveryStatus_lower(_ value: DeliveryStatus) -> RustBuffer {
    return FfiConverterTypeDeliveryStatus.lower(value)
}


extension DeliveryStatus: Equatable, Hashable {}







public enum EchoMeshError: Swift.Error {

    
    
    case InvalidKeyLength(expected: UInt32, actual: UInt32
    )
    case HandshakeTimeout(String
    )
    case HandshakeUnexpectedEof(String
    )
    case NoiseError(String
    )
    case ConnectionError(String
    )
    case RuntimeError(String
    )
    case StorageError(String
    )
    case NotReady
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEchoMeshError: FfiConverterRustBuffer {
    typealias SwiftType = EchoMeshError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EchoMeshError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidKeyLength(
            expected: try FfiConverterUInt32.read(from: &buf), 
            actual: try FfiConverterUInt32.read(from: &buf)
            )
        case 2: return .HandshakeTimeout(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .HandshakeUnexpectedEof(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .NoiseError(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .ConnectionError(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .RuntimeError(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .StorageError(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .NotReady

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EchoMeshError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidKeyLength(expected,actual):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(expected, into: &buf)
            FfiConverterUInt32.write(actual, into: &buf)
            
        
        case let .HandshakeTimeout(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .HandshakeUnexpectedEof(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .NoiseError(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConnectionError(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .RuntimeError(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .StorageError(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case .NotReady:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEchoMeshError_lift(_ buf: RustBuffer) throws -> EchoMeshError {
    return try FfiConverterTypeEchoMeshError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEchoMeshError_lower(_ value: EchoMeshError) -> RustBuffer {
    return FfiConverterTypeEchoMeshError.lower(value)
}


extension EchoMeshError: Equatable, Hashable {}




extension EchoMeshError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum NetworkState {
    
    case offline
    case connecting
    case connectedRealityRelay
    case connectedBleMeshFallback
}


#if compiler(>=6)
extension NetworkState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNetworkState: FfiConverterRustBuffer {
    typealias SwiftType = NetworkState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NetworkState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .offline
        
        case 2: return .connecting
        
        case 3: return .connectedRealityRelay
        
        case 4: return .connectedBleMeshFallback
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NetworkState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .offline:
            writeInt(&buf, Int32(1))
        
        
        case .connecting:
            writeInt(&buf, Int32(2))
        
        
        case .connectedRealityRelay:
            writeInt(&buf, Int32(3))
        
        
        case .connectedBleMeshFallback:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetworkState_lift(_ buf: RustBuffer) throws -> NetworkState {
    return try FfiConverterTypeNetworkState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetworkState_lower(_ value: NetworkState) -> RustBuffer {
    return FfiConverterTypeNetworkState.lower(value)
}


extension NetworkState: Equatable, Hashable {}









public protocol CoreEventsListener: AnyObject, Sendable {
    
    func onStateChanged(state: NetworkState) 
    
    func onMessageReceived(message: MessageRecord) 
    
    func onMessageStatusUpdated(messageId: String, status: DeliveryStatus) 
    
    func onPacketReceived(sender: Data, data: Data) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceCoreEventsListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceCoreEventsListener] = [UniffiVTableCallbackInterfaceCoreEventsListener(
        onStateChanged: { (
            uniffiHandle: UInt64,
            state: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreEventsListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStateChanged(
                     state: try FfiConverterTypeNetworkState_lift(state)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onMessageReceived: { (
            uniffiHandle: UInt64,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreEventsListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessageReceived(
                     message: try FfiConverterTypeMessageRecord_lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onMessageStatusUpdated: { (
            uniffiHandle: UInt64,
            messageId: RustBuffer,
            status: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreEventsListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onMessageStatusUpdated(
                     messageId: try FfiConverterString.lift(messageId),
                     status: try FfiConverterTypeDeliveryStatus_lift(status)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPacketReceived: { (
            uniffiHandle: UInt64,
            sender: RustBuffer,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreEventsListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPacketReceived(
                     sender: try FfiConverterData.lift(sender),
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceCoreEventsListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface CoreEventsListener: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitCoreEventsListener() {
    uniffi_echomesh_core_fn_init_callback_vtable_coreeventslistener(UniffiCallbackInterfaceCoreEventsListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceCoreEventsListener {
    fileprivate static let handleMap = UniffiHandleMap<CoreEventsListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceCoreEventsListener : FfiConverter {
    typealias SwiftType = CoreEventsListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCoreEventsListener_lift(_ handle: UInt64) throws -> CoreEventsListener {
    return try FfiConverterCallbackInterfaceCoreEventsListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCoreEventsListener_lower(_ v: CoreEventsListener) -> UInt64 {
    return FfiConverterCallbackInterfaceCoreEventsListener.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeContact: FfiConverterRustBuffer {
    typealias SwiftType = [Contact]

    public static func write(_ value: [Contact], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeContact.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Contact] {
        let len: Int32 = try readInt(&buf)
        var seq = [Contact]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeContact.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeConversationSummary: FfiConverterRustBuffer {
    typealias SwiftType = [ConversationSummary]

    public static func write(_ value: [ConversationSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeConversationSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ConversationSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [ConversationSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeConversationSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessageRecord: FfiConverterRustBuffer {
    typealias SwiftType = [MessageRecord]

    public static func write(_ value: [MessageRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessageRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MessageRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [MessageRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessageRecord.read(from: &buf))
        }
        return seq
    }
}
public func derivePublicKey(privateKey: Data)throws  -> IdentityKeyPair  {
    return try  FfiConverterTypeIdentityKeyPair_lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_func_derive_public_key(
        FfiConverterData.lower(privateKey),$0
    )
})
}
public func generateIdentityKeypair()throws  -> IdentityKeyPair  {
    return try  FfiConverterTypeIdentityKeyPair_lift(try rustCallWithError(FfiConverterTypeEchoMeshError_lift) {
    uniffi_echomesh_core_fn_func_generate_identity_keypair($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_echomesh_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_echomesh_core_checksum_func_derive_public_key() != 61285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_func_generate_identity_keypair() != 29642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_add_contact() != 48969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_connect() != 40480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_current_state() != 50013) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_disconnect() != 57636) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_get_contacts() != 11426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_get_conversations() != 47464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_get_messages() != 4464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_ping_ms() != 19271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_send_chat_message() != 41624) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_send_message() != 46583) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_send_packet() != 16894) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_shutdown() != 4146) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_echomeshclient_storage_path() != 26240) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_constructor_echomeshclient_new() != 46168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_coreeventslistener_on_state_changed() != 27739) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_coreeventslistener_on_message_received() != 12372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_coreeventslistener_on_message_status_updated() != 8847) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_echomesh_core_checksum_method_coreeventslistener_on_packet_received() != 48419) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitCoreEventsListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureEchomeshCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all